// Downloads the Mutopia Project pieces listed in src/midi/mutopia.json into public/songs/mutopia/
// and writes their attribution (maintainer + license) to public/licenses/sheet-music.txt.
// Run manually after editing the list: `node tools/mutopia.mjs`. Needs network; not part of the build.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import tonejs from "@tonejs/midi";

const { Midi } = tonejs;
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const list = JSON.parse(readFileSync(join(root, "src/midi/mutopia.json"), "utf8"));
const outDir = join(root, "public/songs/mutopia");
mkdirSync(outDir, { recursive: true });

const text = (s) =>
  s
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();

const ids = new Set();
const lines = [];
let failed = 0;
for (const p of list) {
  if (ids.has(p.id)) throw new Error(`Duplicate id ${p.id}`);
  ids.add(p.id);
  const page = `https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=${p.m}`;
  try {
    const html = await (await fetch(page)).text();
    const mid = /href="([^"]+\.mid)"/.exec(html)?.[1];
    const license = text(/<b>Copyright:<\/b>([\s\S]*?)<\/td>/.exec(html)?.[1] ?? "");
    const maintainer = text(/<b>Maintainer:<\/b>([\s\S]*?)<\/td>/.exec(html)?.[1] ?? "");
    const heading = text(/<h2>([\s\S]*?)<\/h2>/.exec(html)?.[1] ?? p.title);
    const by = text(/<h4>([\s\S]*?)<\/h4>/.exec(html)?.[1] ?? "");
    if (!mid || !license) throw new Error("piece page not recognised");
    const file = join(outDir, `${p.id}.mid`);
    if (!existsSync(file)) {
      const res = await fetch(mid);
      if (!res.ok) throw new Error(`MIDI HTTP ${res.status}`);
      writeFileSync(file, Buffer.from(await res.arrayBuffer()));
    }
    const m = new Midi(readFileSync(file));
    const tracks = m.tracks.filter((t) => t.notes.length);
    const notes = tracks.reduce((n, t) => n + t.notes.length, 0);
    p.seconds = Math.round(Math.max(...tracks.flatMap((t) => t.notes.map((n) => n.time + n.duration))));
    p.notes = notes;
    console.log(`${p.id.padEnd(26)} ${String(Math.round(m.duration)).padStart(4)}s ${String(notes).padStart(5)} notes ${tracks.length} tr  ${license}`);
    lines.push(
      [
        `${heading} — ${by}`,
        `  File: songs/mutopia/${p.id}.mid (unmodified)`,
        `  Typeset by: ${maintainer || "Mutopia Project contributors"}`,
        `  License: ${license}`,
        `  Source: ${page}`,
      ].join("\n")
    );
  } catch (e) {
    failed++;
    console.error(`FAILED ${p.id} (Mutopia ${p.m}): ${e.message}`);
  }
}

const header = `Sheet music / MIDI from the Mutopia Project (https://www.mutopiaproject.org)
=========================================================================

The pieces below are bundled with Sonatrio as unmodified MIDI files generated by the
Mutopia Project from its free editions. The compositions themselves are in the public
domain; each edition is distributed by Mutopia under the license shown (Public Domain,
Creative Commons Attribution, or Creative Commons Attribution-ShareAlike). Files under a
Creative Commons license are redistributed under that same license:
  CC BY 3.0      https://creativecommons.org/licenses/by/3.0/
  CC BY-SA 2.5   https://creativecommons.org/licenses/by-sa/2.5/
  CC BY-SA 3.0   https://creativecommons.org/licenses/by-sa/3.0/
  CC BY-SA 4.0   https://creativecommons.org/licenses/by-sa/4.0/
The Mutopia Project and its volunteers provide this material "as is", without warranty.

`;
writeFileSync(join(root, "public/licenses/sheet-music.txt"), header + lines.join("\n\n") + "\n");
writeFileSync(join(root, "src/midi/mutopia.json"), `[\n${list.map((p) => `  ${JSON.stringify(p)}`).join(",\n")}\n]\n`);
console.log(`\n${lines.length} pieces written${failed ? `, ${failed} failed` : ""}.`);
if (failed) process.exitCode = 1;
